python ../bleu.py eval_full/0.txt coco.txt
python ../bleu.py eval_full/10.txt coco.txt
python ../bleu.py eval_full/20.txt coco.txt
python ../bleu.py eval_full/30.txt coco.txt
python ../bleu.py eval_full/40.txt coco.txt
python ../bleu.py eval_full/50.txt coco.txt
python ../bleu.py eval_full/60.txt coco.txt
python ../bleu.py eval_full/70.txt coco.txt
python ../bleu.py eval_full/80.txt coco.txt
python ../bleu.py eval_full/90.txt coco.txt
python ../bleu.py eval_full/100.txt coco.txt
python ../bleu.py eval_full/110.txt coco.txt
python ../bleu.py eval_full/120.txt coco.txt
python ../bleu.py eval_full/130.txt coco.txt
python ../bleu.py eval_full/140.txt coco.txt
python ../bleu.py eval_full/150.txt coco.txt
python ../bleu.py eval_full/160.txt coco.txt
python ../bleu.py eval_full/170.txt coco.txt
python ../bleu.py eval_full/180.txt coco.txt
python ../bleu.py eval_full/0.eval.txt coco.eval.txt
python ../bleu.py eval_full/10.eval.txt coco.eval.txt
python ../bleu.py eval_full/20.eval.txt coco.eval.txt
python ../bleu.py eval_full/30.eval.txt coco.eval.txt
python ../bleu.py eval_full/40.eval.txt coco.eval.txt
python ../bleu.py eval_full/50.eval.txt coco.eval.txt
python ../bleu.py eval_full/60.eval.txt coco.eval.txt
python ../bleu.py eval_full/70.eval.txt coco.eval.txt
python ../bleu.py eval_full/80.eval.txt coco.eval.txt
python ../bleu.py eval_full/90.eval.txt coco.eval.txt
python ../bleu.py eval_full/100.eval.txt coco.eval.txt
python ../bleu.py eval_full/110.eval.txt coco.eval.txt
python ../bleu.py eval_full/120.eval.txt coco.eval.txt
python ../bleu.py eval_full/130.eval.txt coco.eval.txt
python ../bleu.py eval_full/140.eval.txt coco.eval.txt
python ../bleu.py eval_full/150.eval.txt coco.eval.txt
python ../bleu.py eval_full/160.eval.txt coco.eval.txt
python ../bleu.py eval_full/170.eval.txt coco.eval.txt
python ../bleu.py eval_full/180.eval.txt coco.eval.txt
